In [9]:
# code below is for updating database file

from CogBook import load_profiles_from_file, save_profiles_to_file, Profile, get_descriptors
from PIL import Image

import pickle
import numpy as np
import os



# assign directory
directory = '../Images'

# iterate over files in
# that directory
fileList = []

for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    if os.path.isfile(f):
        fileList.append((f, filename))


profileDB = load_profiles_from_file()


for fileInfo in fileList:
    print(fileInfo[1])

    name, number = fileInfo[1].split(".")[0].split("_")
    
    img_data = np.array(Image.open(fileInfo[0]))[:,:,:3]
    
    

    

alan_1.png
[[[ 22  16  16]
  [ 21  17  17]
  [ 20  17  17]
  ...
  [114  97  66]
  [114  98  66]
  [116  99  68]]

 [[ 22  16  16]
  [ 21  16  16]
  [ 20  17  17]
  ...
  [114  98  66]
  [115  98  66]
  [115  99  67]]

 [[ 22  17  18]
  [ 21  17  17]
  [ 21  17  18]
  ...
  [115  97  66]
  [115  97  66]
  [115  98  67]]

 ...

 [[158 135 103]
  [158 135 103]
  [159 136 101]
  ...
  [ 62  48  21]
  [ 61  47  22]
  [ 60  47  24]]

 [[158 134 105]
  [158 134 103]
  [158 135 102]
  ...
  [ 60  46  23]
  [ 59  46  24]
  [ 58  45  26]]

 [[158 135 108]
  [158 135 107]
  [159 136 105]
  ...
  [ 56  43  22]
  [ 55  42  23]
  [ 54  41  24]]]
evan_2.png
[[[ 18   8   9]
  [ 18   8   9]
  [ 18   8   9]
  ...
  [172 172 163]
  [154 155 146]
  [154 156 147]]

 [[ 19   9  10]
  [ 19   9  10]
  [ 19   9  10]
  ...
  [136 142 135]
  [118 125 118]
  [111 119 112]]

 [[ 19   9  10]
  [ 19   9  10]
  [ 19   9  10]
  ...
  [101 116 112]
  [ 98 113 109]
  [ 97 112 108]]

 ...

 [[241 140 154]
  [231 127 142